# Introduction


NumPy is the fundamental package for scientific computing with Python. It provides N-dimensional array object (ndarray), broadcasting for array operations, and standard mathematical functions for fast operations.

In [9]:
#Importing Libraries
import numpy as np

# Basic Array Creation and Inspection

In [2]:


# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)

# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("2D Array:\n", arr_2d)

# Check dimensions, shape, and data type
print("Number of dimensions:", arr_2d.ndim)
print("Shape of array:", arr_2d.shape)
print("Data type:", arr_2d.dtype)


1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Number of dimensions: 2
Shape of array: (2, 3)
Data type: int32


## Array Operations

In [3]:
# Element-wise operations
arr = np.array([10, 20, 30, 40])
print("Original:", arr)
print("Add 5:", arr + 5)
print("Multiply by 2:", arr * 2)
print("Square:", arr ** 2)

# Broadcasting example
arr_a = np.array([[1, 2, 3],
                  [4, 5, 6]])
arr_b = np.array([10, 20, 30])

print("Broadcasted sum:\n", arr_a + arr_b)


Original: [10 20 30 40]
Add 5: [15 25 35 45]
Multiply by 2: [20 40 60 80]
Square: [ 100  400  900 1600]
Broadcasted sum:
 [[11 22 33]
 [14 25 36]]


# Slicing, Indexing, and Statistical Methods

In [8]:
# Slicing & indexing
arr = np.arange(10)  # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print("Elements 2 to 5:", arr[2:6])
print("Even indices:", arr[::2])  # step of 2

# Statistical functions
print("Mean:", arr.mean())
print("Standard Deviation:", arr.std())
print("Sum:", arr.sum())
print("Max value:", arr.max())


Elements 2 to 5: [2 3 4 5]
Even indices: [0 2 4 6 8]
Mean: 4.5
Standard Deviation: 2.8722813232690143
Sum: 45
Max value: 9
